### ISSUE TITLE
Customer Info blank within Braintree dashboard

### ISSUE THREAD

**Issue by zackspear** [KuriousAgency/commerce-braintree#9]
In the Braintree dashboard do you know if there's a way to submit the user details (name & email, craft order/reference #, etc.) as a part of the "Customer Info" for the transaction? Currently blank for both address and address-less transactions. This way we can cross reference orders within Craft Commerce to Braintree if need be.

Cheers

**Comment by samuelbirch** [comment]
We'll use the order->shortNumber for the orderId as that will make searching easier, we can't use the order->reference as that is not generated until after the order is completed.

For guest checkout, only the email will be sent in the customer info.

If the customer is in the vault, we'll link to that otherwise we'll send email, firstname & lastName as the customer info.

**Comment by samuelbirch** [comment]
released in v2.2.1

**Comment by zackspear** [comment]
Cheers!

I’ll test this out sometime today and will let you know if we have any trouble. 

Thanks again for the quick turn around on all these. 🙏
